// <auto-generated />
namespace Intelemark.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RelationRemoveContactIdAnsweredForm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RelationRemoveContactIdAnsweredForm));
        
        string IMigrationMetadata.Id
        {
            get { return "201807272310566_RelationRemove-ContactIdAnsweredForm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
