// <auto-generated />
namespace Intelemark.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RecordsCallCodesAnsweredForms : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RecordsCallCodesAnsweredForms));
        
        string IMigrationMetadata.Id
        {
            get { return "201807251819445_Records-CallCodes-AnsweredForms"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
