// <auto-generated />
namespace Intelemark.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AnswerQuestionv3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AnswerQuestionv3));
        
        string IMigrationMetadata.Id
        {
            get { return "201807171909538_Answer-Questionv3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
