// <auto-generated />
namespace Intelemark.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RelationRecordAnsweredForm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RelationRecordAnsweredForm));
        
        string IMigrationMetadata.Id
        {
            get { return "201807272321049_Relation-RecordAnsweredForm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
